package smolyanVote.virtualMajor.viewsAndDTO;

import java.util.List;
import java.util.Map;

/**
 * DTO representing a game event generated by AI.
 * Mirrors the frontend GameEvent interface.
 */
public class GameEventDTO {

    private String title;
    private String description;
    private String type; // daily, economic, strategic, emergency
    private String targetRegion; // Optional: specific region affected
    private List<EventOptionDTO> options;

    // ===== NESTED DTO =====

    public static class EventOptionDTO {
        private String label;
        private Map<String, Integer> impact; // Resource impacts
        private String consequence;
        private Map<String, Integer> regionImpact; // Optional: regional impact

        public EventOptionDTO() {
        }

        public String getLabel() {
            return label;
        }

        public void setLabel(String label) {
            this.label = label;
        }

        public Map<String, Integer> getImpact() {
            return impact;
        }

        public void setImpact(Map<String, Integer> impact) {
            this.impact = impact;
        }

        public String getConsequence() {
            return consequence;
        }

        public void setConsequence(String consequence) {
            this.consequence = consequence;
        }

        public Map<String, Integer> getRegionImpact() {
            return regionImpact;
        }

        public void setRegionImpact(Map<String, Integer> regionImpact) {
            this.regionImpact = regionImpact;
        }
    }

    // ===== CONSTRUCTORS =====

    public GameEventDTO() {
    }

    // ===== GETTERS AND SETTERS =====

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTargetRegion() {
        return targetRegion;
    }

    public void setTargetRegion(String targetRegion) {
        this.targetRegion = targetRegion;
    }

    public List<EventOptionDTO> getOptions() {
        return options;
    }

    public void setOptions(List<EventOptionDTO> options) {
        this.options = options;
    }
}
