export { MessengerRoot } from "./components/MessengerRoot";
export { MessengerFab } from "./components/MessengerFab";
export { MessageUserButton } from "./components/MessageUserButton";
export { messengerApi } from "./api";
export { useConversations } from "./hooks/useConversations";
export { useUnreadCount } from "./hooks/useUnreadCount";
export { useStartConversation } from "./hooks/useStartConversation";
export { useMessengerUiStore } from "./store/messengerUiStore";
export { useIsDesktopMessenger } from "./lib/isDesktopMessenger";
export type { Conversation, Message, MessengerUser } from "./types";
