# PowerShell script to setup Android SDK location
# This script tries to find Android SDK and updates local.properties

Write-Host "🔍 Searching for Android SDK..." -ForegroundColor Cyan

$sdkPaths = @(
    "$env:LOCALAPPDATA\Android\Sdk",
    "$env:USERPROFILE\AppData\Local\Android\Sdk",
    "C:\Users\$env:USERNAME\AppData\Local\Android\Sdk",
    "$env:ANDROID_HOME",
    "$env:ANDROID_SDK_ROOT",
    "C:\Android\Sdk",
    "C:\Program Files\Android\Sdk"
)

$foundSdk = $null

foreach ($path in $sdkPaths) {
    if ($path -and (Test-Path $path)) {
        $platformTools = Join-Path $path "platform-tools"
        if (Test-Path $platformTools) {
            Write-Host "✅ Found Android SDK at: $path" -ForegroundColor Green
            $foundSdk = $path
            break
        }
    }
}

if (-not $foundSdk) {
    Write-Host "❌ Android SDK not found!" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please install Android Studio and Android SDK:" -ForegroundColor Yellow
    Write-Host "1. Download Android Studio from: https://developer.android.com/studio" -ForegroundColor Yellow
    Write-Host "2. Install Android Studio" -ForegroundColor Yellow
    Write-Host "3. Open Android Studio -> SDK Manager" -ForegroundColor Yellow
    Write-Host "4. Install Android SDK (API Level 24+)" -ForegroundColor Yellow
    Write-Host "5. Run this script again" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Or set ANDROID_HOME environment variable manually:" -ForegroundColor Yellow
    Write-Host '  $env:ANDROID_HOME = "C:\Users\YourUsername\AppData\Local\Android\Sdk"' -ForegroundColor Yellow
    exit 1
}

# Convert Windows path to Unix-style path for Gradle
$sdkDir = $foundSdk -replace '\\', '/'

Write-Host "📝 Updating local.properties..." -ForegroundColor Cyan

$localProperties = @"
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=$sdkDir

"@

Set-Content -Path "local.properties" -Value $localProperties -Encoding UTF8

Write-Host "✅ local.properties updated successfully!" -ForegroundColor Green
Write-Host "   SDK location: $sdkDir" -ForegroundColor Green
Write-Host ""
Write-Host "You can now run: npm run android" -ForegroundColor Cyan

